title: Sun Praising 101
author: Data_Expunged
email: cjohn2@ocdsb.ca
description: > # this means to ignore newlines until "baseurl:"
  Praising the sun is an important part of many warriors' lives, 
  thus a proper method is required for proper sun praising. 
  this site will provide a step by step process on how to 
  properly praise the sun.

# social links
github_username: DataExpunged

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
